In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Salary_Data.csv')

In [3]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
X=df.iloc[:,0].values
y=df.iloc[:,1].values

In [5]:
X

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [6]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [7]:
X_mean = np.mean(X)
X_mean

5.3133333333333335

In [8]:
y_mean = np.mean(y)
y_mean

76003.0

In [9]:
up = (X-X_mean)*(y-y_mean)

In [10]:
up

array([ 1.54460800e+05,  1.19589307e+05,  1.45943893e+05,  1.07610440e+05,
        1.12428693e+05,  4.67245467e+04,  3.66732733e+04,  4.55592400e+04,
        2.44259067e+04,  3.03532533e+04,  1.80694667e+04,  2.65411533e+04,
        2.50137467e+04,  2.29586933e+04,  1.21121600e+04,  3.33353333e+03,
        2.12778667e+03, -9.44666667e+01,  3.14453333e+03,  1.23167400e+04,
        2.33927000e+04,  3.97890667e+04,  6.54400800e+04,  1.09141980e+05,
        1.13209493e+05,  1.09047913e+05,  1.71510987e+05,  1.57029173e+05,
        2.31321493e+05,  2.37907213e+05])

In [11]:
down = (X-X_mean)**2

In [12]:
down

array([1.77521778e+01, 1.61068444e+01, 1.45415111e+01, 1.09781778e+01,
       9.69284444e+00, 5.82417778e+00, 5.35151111e+00, 4.46617778e+00,
       4.46617778e+00, 2.60284444e+00, 1.99751111e+00, 1.72484444e+00,
       1.72484444e+00, 1.47217778e+00, 6.61511111e-01, 1.70844444e-01,
       4.55111111e-02, 1.77777778e-04, 3.44177778e-01, 4.71511111e-01,
       2.21017778e+00, 3.19217778e+00, 6.69084444e+00, 8.33284444e+00,
       1.14695111e+01, 1.35915111e+01, 1.75281778e+01, 1.83755111e+01,
       2.48668444e+01, 2.69015111e+01])

In [13]:
m = up.sum()/down.sum()
m

9449.962321455077

In [14]:
# y_mean = (m*X_mean) + c
# c = y_mean - (m*X_mean)

c=y_mean-(m*X_mean)

In [15]:
c

25792.20019866869

In [16]:
res = []
for i in range(len(X)):
    res.append(round(m*X[i]+c,2))
res = np.array(res)

In [17]:
res = np.array(res)

In [18]:
res

array([ 36187.16,  38077.15,  39967.14,  44692.12,  46582.12,  53197.09,
        54142.09,  56032.08,  56032.08,  60757.06,  62647.05,  63592.05,
        63592.05,  64537.05,  68317.03,  72097.02,  73987.01,  75877.  ,
        81546.98,  82491.97,  90051.94,  92886.93, 100446.9 , 103281.89,
       108006.87, 110841.86, 115566.84, 116511.84, 123126.81, 125016.8 ])

In [19]:
# making a Class for LinearRegession
class LinearRegression:
    def __init__(my):
        my.up=0
        my.down=0
        my.m=0
        my.c=0
    def fit(my,X,y):
        X_mean = np.mean(X)
        y_mean = np.mean(y)
        my.up = (X-X_mean)*(y-y_mean)
        my.down = (X-X_mean)**2
        my.m = my.up.sum()/my.down.sum()
        my.c = y_mean - (my.m * X_mean)
    def predict(my,X):
        res = []
        for i in range(len(X)):
            res.append(round(m*X[i]+c,2))
        res = np.array(res)
        return res

## Testing the model

In [20]:
lr = LinearRegression()

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [22]:
lr.fit(X_train,y_train)

In [23]:
y_pred=lr.predict(X_test)
y_pred

array([ 54142.09, 125016.8 , 108006.87,  36187.16,  46582.12,  56032.08])

In [24]:
## Let's see the accuracy score
from sklearn.metrics import r2_score
accuracy=r2_score(y_test,y_pred)*100

In [25]:
accuracy

97.19296445253227