In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')

In [2]:
df = pd.read_csv('logistic_reg_dataset.txt',sep=',')

In [3]:
df

Marks_1    Marks_2  Result
0   34.623660  78.024693       0
1   30.286711  43.894998       0
2   35.847409  72.902198       0
3   60.182599  86.308552       1
4   79.032736  75.344376       1
..        ...        ...     ...
95  83.489163  48.380286       1
96  42.261701  87.103851       1
97  99.315009  68.775409       1
98  55.340018  64.931938       1
99  74.775893  89.529813       1

[100 rows x 3 columns]

In [4]:
df.shape

(100, 3)

In [5]:
X = df.iloc[:,0:2].values
y = df.iloc[:,-1].values

In [6]:
m,n_f = X.shape
b = 0

In [7]:
w = np.zeros(n_f)
w

array([0., 0.])

In [8]:
z = np.dot(X,w)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
a = 1/(1+np.exp(-z))
a

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [10]:
dz = a - y
dz

array([ 0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5,  0.5,
        0.5, -0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5,
        0.5,  0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5, -0.5, -0.5,  0.5,
       -0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5, -0.5,  0.5, -0.5,  0.5,
        0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5,
        0.5, -0.5,  0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,  0.5,  0.5,
       -0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,
       -0.5,  0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5, -0.5,
       -0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,
       -0.5])

In [11]:
dw = np.dot(dz,X)/m
dw

array([-12.00921659, -11.26284221])

In [12]:
db = np.sum(dz)/m
db

-0.1

In [13]:
w -= 0.001*dw
w

array([0.01200922, 0.01126284])

In [14]:
b -= 0.001*db
b

0.0001

In [15]:
m,n_f = X.shape
b = 0
w = np.zeros(n_f)
for _ in range(100000):
    z = np.dot(X,w)
    a = 1/(1+np.exp(-z))
    dz = a - y
    dw = np.dot(dz,X)/m
    db = np.sum(dz)/m
    w = w - 0.001*dw
    b = b - 0.001*db

In [16]:
print(w)
print(b)

[0.01042527 0.00045203]
-6.98355461619167


# Making a class for logistic regression.......

In [17]:
class logistic_reg():
    def __init__(my,w=0,b=0,learning_rate=0.001,evolution=100000):
        my.w=w
        my.b=b
        my.lr=learning_rate
        my.cycle = evolution
    
    def fit(my,X,y):
        my.w = np.zeros(X.shape[1])
        m,n_f = X.shape
        for _ in range(my.cycle):
            a = my.sigmoid_func(np.dot(X,my.w))
            dw = np.dot((a-y),X)/m
            db = np.sum(a-y)/m
            my.w = my.w - my.lr*dw
            my.b = my.b - my.lr*db
        return my
    
    def sigmoid_func(my,a):
        return 1/(1 + np.exp(-a))
    
    def predict(my,predict):
        result = my.sigmoid_func(np.dot(predict,my.w))
        result = np.array([1 if i>0.5 else int(0) for i in result])
        return result

# Testing ...

In [18]:
mylr = logistic_reg(learning_rate=0.001,evolution=100000)

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=3)

In [20]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(90, 2)
(10, 2)
(90,)
(10,)


In [21]:
mylr.fit(X_train,y_train)

In [22]:
y_pred = mylr.predict(X_test)

In [23]:
accuracy_score(y_test,y_pred)

0.8

In [24]:
y_test

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [25]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])